### PR TITLE
update astropy-helpers

### PR DESCRIPTION
**Pull request by keflavich**
to v0.4.8

### CODE REVIEW

**Comment by astrofrog** [comment]
You need to also copy the updated ``ah_bootstrap.py``

**Comment by astrofrog** [comment]
Why not v1.0.1 out of curiosity?

**Comment by keflavich** [comment]
Purely a mistake... I saw '0.4' and somehow parsed it as '0.4.8 > 1.0.1'.  Good thing I PR'd this one.  Fixing now.

**Comment by keflavich** [comment]
@astrofrog it looks like ah_bootstrap is already up to date?  At least, checking it out and diffing on the command line don't seem to notice any differences

**Comment by astrofrog** [comment]
The ah_bootstrap.py 1.0.1 should be quite different to the one that was here before, for example the 1.0.1 file should include this block:

```
# matplotlib can cause problems if it is imported from within a call of
# run_setup(), because in some circumstances it will try to write to the user's
# home directory, resulting in a SandboxViolation.  See
# https://github.com/matplotlib/matplotlib/pull/4165
# Making sure matplotlib, if it is available, is imported early in the setup
# process can mitigate this (note importing matplotlib.pyplot has the same
# issue)
try:
    import matplotlib.pyplot
except:
    # Ignore if this fails for *any* reason*
    pass
```

that I don't see in ``pvextractor``. Did you try doing:

```
cp astropy_helpers/ah_bootstrap.py .
```
?

**Comment by keflavich** [comment]
Thanks @astrofrog.  I had tried

```
git remote add package-template git://github.com/astropy/package-template.git
git fetch package-template
git checkout package-template/master -- ah_bootstrap.py
```
which did not work / was wrong.  Copying from astropy_helpers worked.

**Pull request merged**
