### PR TITLE
issubclass replaced by isinstance in PVSlicer

### PR DESCRIPTION
**Pull request by lpda**
This is a proposal of fix for the bug reported in the issue 111

### CODE REVIEW

**Comment by keflavich** [comment]
This highlights the need for a test; @lpda would you be willing to write one?

**Comment by lpda** [comment]
@keflavich , I am not quite familiar with testing, but looking at the other tests, I would add two functions to the following files:

1. `test_gui_from_fits_filename` to `pvextractor/tests/test_gui.py`:

```
# Cheating from the function test_gui in pvextractor/tests/test_gui.py

def test_gui_from_fits_filename():

    # This tests currently segfaults with Matplotlib 3.1 and later

    fits_filename = make_test_fits_file()

    pv = PVSlicer(fits_filename, clim=(-0.02, 2), backend='Qt5Agg')
    pv.show(block=False)

    xy_data = np.array([[0.0, 0.1, 0.5, 1.0, 0.5],
                        [0.0, 0.3, 0.4, 0.9, 1.4]]).T

    x, y = pv.ax1.transData.transform(xy_data).T

    for i in range(len(x)):
        pv.fig.canvas.motion_notify_event(x[i], y[i])
        pv.fig.canvas.button_press_event(x[i], y[i], 1)

    pv.fig.canvas.key_press_event('enter')
    pv.fig.canvas.motion_notify_event(x[-1] - 20, y[-1])
    pv.fig.canvas.button_press_event(x[-1] - 20, y[-1], 1)

    pv.fig.canvas.draw()

    assert pv.pv_slice.data.shape == (5, 2)

    pv.close()
```
2. `make_test_fits_file` to `pvextractor/tests/test_slicer.py`:

```
# Taking advantage of the function make_test_hdu in pvextractor/tests/test_slicer.py

def make_test_fits_file():
    hdu = make_test_hdu()
    
    filename = 'example.fits'
    hdu.writeto(filename)
    return filename
```
However, I do not feel comfortable to commit this functions as I think that they should be improved in two aspects:
a. Is it OK to write the file as 'example.fits'? I imagine that there is a "standard" way to write a temporary file which a file with a random available filename (and maybe to delete it when the test has finished?).
b. Should I refactor test_gui and test_gui_from_fits_filename to share a function with the cheated code? In that case, where this shared function should be written? In test_gui.py?

My apologies for submitting a good test directly, but I am not familiar with this kind of details

**Comment by keflavich** [comment]
I meant, add your tests to this PR - we can remove it later if we decide we don't want it, but I think we do.

**Comment by lpda** [comment]
As suggested by @keflavich , I have added the tests to this pull request (I understood that it should be in this PR, and not in a new one, not?).

**Review by e-koch — APPROVED** [review]
Looks good. Agreed with @keflavich that some updates to the testing infrastructure are needed, but that's a separate issue.

**Pull request merged**
