### PR TITLE
change default pv colormap to grayscale

### PR DESCRIPTION
**Pull request by keflavich**
for purpose of better talk figure

### CODE REVIEW

**Comment by astrofrog** [comment]
Aw, why not Viridis?

**Comment by keflavich** [comment]
b/c c&p plt.cm.gray was easier.  viridis is fine - want it instead?
 dropdown would be sweet but that's too hard

On Wed, Mar 23, 2016 at 11:23 AM, Thomas Robitaille <
notifications@github.com> wrote:

> Aw, why not Viridis?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/radio-astro-tools/pvextractor/pull/74#issuecomment-200478672>
>



-- 
Adam

**Comment by astrofrog** [comment]
No, Viridis would require Matplotlib >1.5

**Comment by astrofrog** [comment]
Closing in favor of #95

**Pull request closed without merging**
